theme: just-the-docs
title: Vernieuwing CollectieNederland.nl
description: Het applicatiesprofiel van het vernieuwde platform van CollectieNederland.nl

url: https://collectienederland.github.io/applicatieprofiel/
